model:
    model_name: smart
    lr: 1.0e-4
    optimizer: adam
    max_surface_points: null
    max_volume_points: null
    model_params:
        spatial_dim: 3
        surface_channels: 4
        volume_channels: 4
        parameter_channels: 2
        latent_dim: 192
        latent_geometry_points: 4096
        subsampled_geometry_points: 4096
        num_encoder_decoder_blocks: 12
        num_heads: 8

data:
    type: combined
    n_geometry: null
    n_surface: 32768
    n_volume: 32768
    load_surface: True
    load_volume: True
    batch_size: 1
    num_workers: 8
    pin_memory: True
    prefetch_factor: 2
    num_val: 100
    return_metadata: False
    return_cond: True
    global_cond_norm: True
    vol_stats_name: norm_stats_volume_thinned.npz
    surf_stats_name: norm_stats_centered_thinned.npz
    volume_thin:
        voxel: 0.01
        min_count: 8
        alpha: 1.0
        oversample: 8
    surface_thin:
        voxel: 0.01
        min_count: 8
        alpha: 1.0
        oversample: 8

training:
    seed: 42
    devices: 1
    accelerator: gpu
    strategy: auto
    check_val_every_n_epoch: 5
    val_every_n_steps: 1000
    log_every_n_steps: 10
    max_epochs: 100
    log_dir: ./logs/
    project: cfd_ft_final
    wandb_mode: online
    checkpoint: null
    accumulate_grad_batches: 1
