model:
    model_name: upt
    lr: 1.0e-4
    optimizer: adam
    num_supernodes: 1024
    num_surface_anchors: 4096
    num_volume_anchors: 4096
    max_surface_points: null
    max_volume_points: null
    model_params:
        ndim: 3
        input_dim: 3
        output_dim_surface: 4
        output_dim_volume: 4
        dim: 384
        geometry_depth: 2
        num_heads: 8
        num_cond: 2
        blocks: ppscscs
        num_surface_blocks: 3
        num_volume_blocks: 3
        num_supernodes: 1024
        pooling: erwin

data:
    type: combined
    n_geometry: null
    n_surface: 32768
    n_volume: 32768
    load_surface: True
    load_volume: True
    batch_size: 1
    num_workers: 8
    pin_memory: True
    prefetch_factor: 2
    num_val: 100
    return_metadata: False
    return_cond: True
    global_cond_norm: True
    vol_stats_name: norm_stats_volume_thinned.npz
    surf_stats_name: norm_stats_centered_thinned.npz
    volume_thin:
        voxel: 0.01
        min_count: 8
        alpha: 1.0
        oversample: 8
    surface_thin:
        voxel: 0.01
        min_count: 8
        alpha: 1.0
        oversample: 8

training:
    seed: 42
    devices: 1
    accelerator: gpu
    strategy: auto
    check_val_every_n_epoch: 5
    val_every_n_steps: 1000
    log_every_n_steps: 10
    max_epochs: 100
    log_dir: ./logs/
    project: cfd_ft_final_transolver
    wandb_mode: online
    checkpoint: null
    accumulate_grad_batches: 1
