model:
    model_name: transolver
    lr: 1.0e-4
    optimizer: adam
    model_params:
        space_dim: 3
        n_hidden: 384
        n_layers: 12
        n_head: 8
        mlp_ratio: 4
        slice_num: 32
        out_dim: 4
        split_heads: True
        parameter_channels: 2
        cond_init: zero

data:
    type: combined
    surface_dir: drivaerml/collated
    volume_dir: drivaerml/volume_collated
    n_geometry: null
    n_surface: 32768
    n_volume: 32768
    load_surface: True
    load_volume: True
    batch_size: 1
    num_workers: 8
    pin_memory: True
    prefetch_factor: 4
    num_val: 100
    return_metadata: False
    return_cond: True
    global_cond_norm: True
    volume_thin:
        min_count: 8
        voxel: 0.01
        oversample: 8
    surface_thin:
        min_count: 8
        voxel: 0.01
        oversample: 8
    surf_stats_name: norm_stats_centered_thinned.npz
    vol_stats_name: norm_stats_volume_thinned.npz

training:
    seed: 42
    devices: 1
    accelerator: gpu
    strategy: auto
    description: drivaerml_transolver
    check_val_every_n_epoch: 1
    val_every_n_steps: 1000
    log_every_n_steps: 100
    max_steps: 100000
    lr_decay_every_n_steps: 1000
    log_dir: ./logs/
    project: latent_spaces_final
    wandb_mode: online
    ema_decay: 0.995
    checkpoint: null
    accumulate_grad_batches: 1
    save_every_n_train_steps: 1000
    archive_every_n_train_steps: 25000
